### ISSUE TITLE
Link einfügen via Linkmap geht nicht

### ISSUE THREAD

**Issue by tbaddade** [phoebusryan/rex_redactor#1]
Klicke ich in der Linkmap den Artikel an passiert nichts weiter.

**Comment by phoebusryan** [comment]
Das ist mir bewusst; es gibt eine hacky Lösung dafür, die ich aber ungerne implementieren möchte. Ich warte auf die finale Version von R5 und insbesondere nachfolgenden EP: https://github.com/redaxo/redaxo/issues/445

**Comment by tbaddade** [comment]
Da man bereits Bilder einfügen kann, schien es, dass du dich zunächst für die Hackylösung entscheiden hattest. Warten wir mal den EP ab.

**Comment by phoebusryan** [comment]
das mit den bildern/links einfügen funktioniert aktuell nur auf der rootseite der linkmap/des medienpools.
wenn man eine andere kategorie auswählt werden die parameter verworfen

ich baue nun aber eine lösung die auch ohne den EP auskommt (wenn auch etwas eingeschränkt) und update es dann nochmals wenn der EP da ist

**Comment by phoebusryan** [comment]
grade version 1.0.4 hochgeladen; damit sollte die linkmap und bilder einfügen gehen. link auf dateien habe ich dafür komplett deaktiviert für den moment

es muss dafür einfach das neue beispielmodul (input) übernommen werden

**Comment by jfax** [comment]
Ich hab das Problem, dass bei rex_linkmap im Editor zwar sehr wohl Das Linkmapfenster aufgeht, wenn ich einen Artikel übernehmen möchte, tut sich nichts und mein Firebug meldet: TypeError: window.opener.document.getElementById(...) is null window.opener.document.getElementById("rv42_NAME").value = name;
Ich kann also keine internen Hyperlinks setzen. Ich hab die aktuelle Version 1.5.5

**Comment by phoebusryan** [comment]
Hat dein Editor eine ID? Kannst du mal dein Module-Input posten?

**Comment by jfax** [comment]
Input ist via mForm: 
`$objForm->addTextAreaField(2,array('class' => 'redactorEditor-full', 'id' => 'redactor_1'));`
Im Firebug produziert das:
`<textarea id="rv42" class="redactorEditor-full" name="REX_INPUT_VALUE[2]" style="display: none;" dir="ltr">`
Dank

**Comment by phoebusryan** [comment]
Ja dann ist ja klar wo der Fehler ist. Die ID muss mit redactor_ beginnen. Siehe Tab "Erklärung" im AddOn. Das lässt sich aktuell nicht umgehen.

**Comment by jfax** [comment]
Natürlich, danke. Dann lässt sich aktuell mForm mit Redactor ohne Hack nicht nutzen, da mForm bei Textareas keine ID-Vergabe zulässt, sondern hart eine ID beginnend mit rv erzeugt. Ich sag dort Bescheid. Danke für Deine Antwort.

**Comment by jfax** [comment]
Nächste Schwierigkeit, passend zum Thema, daher noch hier: **Eigenes Addon** und Textarea mit 
`rex_form::factory` und `addTextareaField`. Hier produziert die Textarea automatisch eine ID der Form: `[addonname]-editieren-[db-feld]`. 

Es ist zwar möglich, der Textarea eine eigene ID (beginnend mit redactor_) mitzugeben:
`$field = $form->addTextareaField('db-feld', NULL, array('rows' => 5, 'id' => 'redactor_meindbfeldname', 'class' => 'redactorEditor-full'));`

Jedoch wird in der Ausgabe die `id="redactor_meindbfeldname"` umgeschrieben in `id="redactor-meindbfeldname"`, also mit Minus dazwischen. 

**Interimslösung:** In der boot.php ein Javascript referenzieren:

```
<?php
if (rex::isBackend())
{
    if (rex_request('func', 'string') == 'edit' or rex_request('func', 'string') == 'add')
    {
        rex_view::addJsFile('/resources/private/backend/js/backend.js');
    }
}
```

und dort die ID per jQuery manipulieren:

```
jQuery(function () {
    $("[id^=redactor-]").attr('id','redactor_' + (new Date).getTime());
});
```

**Comment by phoebusryan** [comment]
Das ist natürlich sehr hässlich von Redaxo. Grundsätzlich ist das aber bald kein Problem mehr, da ich gerade an einer Version arbeite, die ohne IDs läuft. Ich entwickle gerade zusammen mit dem Coreteam eine Lösung dafür. Das Problem an der Sache: Sie benötigt Redaxo 5.1.0 (diese kommt in 2-4 Wochen). Bis dahin kannst du deine Lösung aber gerne nutzen. Danke für den Input.

**Comment by phoebusryan** [comment]
Gefixt in Version 2.0 (wird in einer Woche released)
