### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by tbaddade** [phoebusryan/rex_redactor#11]
Ideen:
- Sprachen wie bei den Rollen als multiple select und mit Checkbox "Alle Sprachen"
- Die Buttons und Plugins jeweils mit Checkbox und wenn nötig ein Textfeld mit den Optionen (so wie bei der Hilfe, nur vorn mit checkbox und hinten das textarea dran.)

**Comment by phoebusryan** [comment]
Die Sprachen werden entfernt demnächst und stattdessen automatisch die Backendsprache genutzt. 

Was genau meinst du mit Punkt 2? Dass man die zusammen klicken kann? Den Gedanken hatte ich auch aber dann kann man die Reihenfolge nicht mehr selber festlegen.

**Comment by tbaddade** [comment]
> Dass man die zusammen klicken kann?

Genau

**Comment by phoebusryan** [comment]
Ich habe dies mit @polarpixel besprochen gehabt damals. Zusammenklicken ist zwar intuitiver aber eben; man kann dann die Reihenfolge nicht mehr festlegen (was ihm persönlich wichtig war).

**Comment by phoebusryan** [comment]
Was ich grundsätzlich machen kann, ist dass man unten in der Hilfe auf die jeweiligen Blöcke/Texte klicken kann und diese dann via Javascript oben eingefügt werden. So analog dem PhpMyAdmin mit den Spalten. Dann müsste man nichts oder weniger tippen und hätte dennoch noch die Flexibilität.

**Comment by tbaddade** [comment]
Oder via DragnDrop  verschieben :)
