### ISSUE TITLE
rows vom textarea werden nicht berücksichtigt

### ISSUE THREAD

**Issue by tbaddade** [phoebusryan/rex_redactor#13]
einfach eine height setzen, `rows x 20px` oder so

**Comment by phoebusryan** [comment]
Ja das ist richtig weil das Ding standardmässig 80px gross ist und bei einer neuen Zeile sich vergrössert. Das ist ein Standardverhalten. Hättest du es lieber, dass es sich nicht vergrössert und stattdessen eine fixe, definierbare Grösse hat? Vermutlich lässt sich dies auch umsetzen.

**Comment by tbaddade** [comment]
> Hättest du es lieber, dass es sich nicht vergrössert und stattdessen eine fixe, definierbare Grösse hat? 

eher so, dass diese 80px eher einen größeren Wert hat. Keine Ahnung warum, aber ich habe jetzt immer erstmal paar Enter reingehauen, damit das größer wird. Ich brauche bei Textfelder immer etwas Luft :)

**Comment by phoebusryan** [comment]
Ich habe die 80px nun auf 250px erhöht. Damit wäre das "Problem" erstmal gelöst oder? Ansonsten könnte ich auch die Möglichkeit einbauen, dass man die Mindestes-Höhe in den Profilen einsetzen kann. Die Frage ist, wie sinnvoll dies wäre.

**Comment by polarpixel** [comment]
Den Gedanken hatte ich auch schon, als ich dieses Issue hier sah. Mir geht es ähnlich wie Thomas, dass Textareas eine gewisse Höhe haben sollten, damit ich mit "wohl" fühle.
Andererseits mag ich es gern, wenn ich da flexibel bin, denn so kann ich durch unterschiedliche Höhen bei z.B. einem normalen Textmodul oder eine Teaserkasten dem Redakteur signalisieren, wo er viel Text reinschreiben darf und wo nur eher wenig.

Das ist natürlich machbar mit einem Inline-CSS-Style, aber die Idee einer Höhenzuweisung im Profil fände ich charmant,

**Comment by phoebusryan** [comment]
Dann könntest du zwei identische Profile anlegen; je nach dem ob der Kunde viel oder wenig Text eingeben soll? Hm. Grundsätzlich gäbe es auch die Möglichkeit eine Zeichenbegrenzung via Plugin einzubauen.

**Comment by polarpixel** [comment]
Ja, hast recht, ist wohl eher Quatsch an der Stelle. Der alte rex_markitup hatte ein Feld, wo man CSS "injizieren" konnte. So könnte man über eine individuelle CSS-Klasse pro Modul unterschiedliche Höhen realisieren. Wäre das vielleicht ein besserer Weg?

Zeichenbegrenzung: Keine schlechte Idee! Man braucht es vermutlich nur sehr selten, aber ich hatte in den letzten Jahren in der Tat 2-3 Fälle, wo ich sowas dann manuell eingebaut hatte. Hätte (für mich) aber keine hohe Priorität.

**Comment by phoebusryan** [comment]
Editorhöhe: Ich kenne den alten Editor für R4 und die Möglichkeit CSS einzufügen, finde diese jedoch sehr unsauber. Eine Klasse, die mitgegeben wird und dafür individueller, ausgelagerter CSS Code wäre definitiv sauberer. Ich überlege mir hier aber noch, was die beste Lösung ist. Fakt ist, dass irgendwas in die Richtung kommen wird.

Zeichenbegrenzung: Dies halte ich grundsätzlich für eine gute Idee. Ich habe deshalb #17 dafür angelegt.

**Comment by phoebusryan** [comment]
Übrigens ist das mit der Editorhöhe grundsätzlich schon möglich. Mit der Standardkonfiguration bekommt die Textarea die Klasse 'redactorEditor-full'. Dieser kann man dann z.b. via CSS "min-height: 1000px;" geben. Es wäre dann aber Profilbasiert und nicht vom Modul abhängig.

Wie sinnvoll ist es, dies so zu lassen und dafür die Möglichkeit, Profile zu kopieren, einzubauen?

**Comment by phoebusryan** [comment]
Gefixt in Version 2.0 (wird in einer Woche released)
