### ISSUE TITLE
Dateiname eines plugins fehlt, daher Fehler beim laden der Datei

### ISSUE THREAD

**Issue by tbaddade** [phoebusryan/rex_redactor#14]
```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (.js, line 0)
/assets/addons/rex_redactor/plugins/.js
```

Version 1.3.10

**Comment by phoebusryan** [comment]
Welches genau? Kannst du mal deine Profilconfig posten?

**Comment by tbaddade** [comment]
Ich habe 2 Profile, deines und ein Eigenes. Da steht nur

`Redactor-Buttons: bold, italic, orderedlist, unorderedlist`

Es scheint aber mehr geladen zu werden als ich angegeben habe. U.a. wird auch `../assets/addons/rex_redactor/langs/de.js` doppelt geladen

![screenshot 2015-12-11 14 35 18](https://cloud.githubusercontent.com/assets/338267/11744913/726edf08-a014-11e5-911c-d2824eefcca5.png)

**Comment by phoebusryan** [comment]
Hast du mehrere profile angelegt?

wie heisst dein plugin? das ist da drin nicht ersichtlich

**Comment by tbaddade** [comment]
> Hast du mehrere profile angelegt?

Ja 2, deines (inital) und meines. Ich hab kein Plugin.

**Comment by phoebusryan** [comment]
Also dass bei zwei Profilen 2x die de.js eingebunden weiss ich. Das Problem ist, dass addCss und addJs kein array_unique nutzt vor der Ausgabe. Wir haben dies mal diskutiert gehabt, aber es ging wohl unter. Es gibt deshalb nun einen Pullrequest (https://github.com/redaxo/redaxo/pull/512) dazu.

Das ganze möchte ich aber eh noch umbauen; siehe #8 

Bzgl. dem leeren Plugin: Schwierig nachzuvollziehen; das passiert bei mir auch mit 5 oder mehr Plugins nicht. Kannst du mir mal ein Testzugang geben?

**Comment by tbaddade** [comment]
Habs. Das taucht auf, wenn man keine Plugins definiert.

**Comment by phoebusryan** [comment]
Super. Danke fürs debuggen. Fix kommt in 1.4.0

**Comment by phoebusryan** [comment]
#8 habe ich gerade auch gefixt in Version 1.4.0
