### ISSUE TITLE
textarea - Profilzuweisung

### ISSUE THREAD

**Issue by tbaddade** [phoebusryan/rex_redactor#15]
Vorschlag:
- id Attribut raus, 
- Profil class raus
- als data-Attribut ala `data-redactor="full"` setzen

**Comment by phoebusryan** [comment]
Den Plan hatte ich auch schon. id ist aktuell aber noch Pflicht (wegen dem fehlenden EP). Die Klasse kann ich aber grundsätzlich mit dem data-Attribut ersetzen.

**Comment by tbaddade** [comment]
Inwiefern brauchst du dafür einen EP?

**Comment by phoebusryan** [comment]
Die ID wird als Referenz für die Linkmap und den Medienpool benutzt. Siehe #1 

Solange der EP dafür nicht vorhanden ist, kann ich die ID nicht entfernen. Die Klasse auf ein data-attribut umzustellen ist aber natürlich möglich. Schlussendlich kommt es aber ja nicht drauf an ob es ein data-Attribut ist oder eine Klasse.

**Comment by tbaddade** [comment]
> Schlussendlich kommt es aber ja nicht drauf an ob es ein data-Attribut ist oder eine Klasse.

richtig. Mir viel nur die unterschiedliche Schreibweise (Groß, klein, _, -) auf und das ich mir das schwerer merken kann. Da kam der Gedanke nur eine Notation zu haben.

Kannst auch gern das Issue schließen.

**Comment by phoebusryan** [comment]
Wie gesagt, die ID kommt definitiv weg sobald der EP vorhanden ist.
