### ISSUE TITLE
Profile : Fehler beim speichern!

### ISSUE THREAD

**Issue by tbaddade** [phoebusryan/rex_redactor#16]
**Version: 1.4.1**

Meldung erscheint nach dem editieren eines Profiles. Leider kommt keine genauere Beschreibung. Woran kann es liegen?

**Comment by tbaddade** [comment]
Liegt an dieser Zeile
https://github.com/factorylabs/rex_redactor/blob/master/pages/profiles.php#L39

Beim hinzufügen eines Profiles wird hier 0 als Id übergeben. Daher hat das neue Profile als Id 0 in der DB und kann später nicht mehr editiert werden. Legt man ein weiteres Profil an, erscheint dann auch der Datensatz des vorherigen Profiles.

**Comment by phoebusryan** [comment]
Ich seh schon. Der Fehler liegt aber nicht an der von dir genannten Zeile, sondern an der Datenbank. Das problem ist, dass AI nicht aktiv ist. Führ mal nachfolgenden Befehl aus (davor die ID 0 löschen und evtl. den AUTO_INCREMENT Wert erhöhen):

ALTER TABLE `%TABLE_PREFIX%markitup_profiles`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

Ich habe dies in der install.sql gerade angepasst. Der fehler wird gefixt in der nächsten Version

**Comment by tbaddade** [comment]
> Der Fehler liegt aber nicht an der von dir genannten Zeile, sondern an der Datenbank.

nein. Es lag daran, dass das Feld `language` in der DB nicht existierte jedoch im Formular noch genutzt wurde.

**Comment by phoebusryan** [comment]
Stimmt. Das kommt noch dazu. Der Fehler kommt von beidem. Das letzte Release habe ich offensichtlich zu schnell rausgehauen. Ein Fix kommt in Kürze.

Danke für die Unterstützung.

**Comment by phoebusryan** [comment]
Gefixt in Version 1.4.2; Release kommt in Kürze. Unbedingt re-installieren via Hauptmenü > AddOns nach dem Update.
