### ISSUE TITLE
formatting als eigene Buttons

### ISSUE THREAD

**Issue by tbaddade** [phoebusryan/rex_redactor#18]
Geht das schon, dass man h[n], p als eigene Buttons darstellen kann, also ohne das Flyout?

**Comment by phoebusryan** [comment]
Nein, der Button Formatting ist sowohl beim Redactor wie auch beim Markitup fix definiert als Flyout. Es können lediglich die Möglichkeiten eingeschränkt werden.

Ich habe dies bereits mal mit @polarpixel angeschaut. Sollte man dies aufteilen in einzelne Buttons hat man dann einfach noch mehr Buttons (es ist jetzt schon teilweise unübersichtlich) und zudem das "Problem", dass man für h1-h6, p etc. eigene Icons benötigt.

**Comment by tbaddade** [comment]
Das Flyout finde ich recht unpraktisch beim editieren. Die optionale Variante wie beim alten markitup fand ich daher sehr sinnvoll. Da konnte jeder für sich das entscheiden. Ich habe meist nur h3 und h4 drin. "p" bräuchte man auch nicht, wenn man die h[n], Listen etc. wieder deaktivert kann es automatisch ein "p" werden.

**Comment by polarpixel** [comment]
Ich war am Anfang ein Freund von einzelnen Buttons, vielleicht auch nur, weil ich es so gewohnt war. Ich muss aber gestehen, dass ich beginne, den Vorteil von Flyouts zu sehen. Mittlerweile habe ich keine klare Präferenz mehr.
@phoebusryan, wenn ich es richtig verstehe, kannst Du beides machen, aber nur "entweder oder"?

**Comment by phoebusryan** [comment]
Ja, klar. Grundsätzlich geht beides. Aus den von mir oben genannten Gründen habe ich mich aber für das Flyout entschieden. Ich kann es auch umstellen, jedoch wären es dann wie gesagt X zusätzliche Buttons und es gibt aktuell keine Icons dafür (rest kommt direkt von font-awesome).

Ich sehe allerdings auch keinen Vorteil in der Liste anstelle des Flyouts.

**Comment by tbaddade** [comment]
> Grundsätzlich geht beides

Warum dann nicht beides anbieten?

**Comment by phoebusryan** [comment]
Weil es sehr mühsam ist dies umzusetzen. Das Formatting ist fest in redactor verankert. Ich kann es zwar aus dem Core rausnehmen und es als flexibles Plugin bauen aber das ist relativ umfangreich.

Sollte es mehrere Leute geben, die dies möchten, werde ich es aber machen.

**Comment by polarpixel** [comment]
Da müssten wir vielleicht mal ein Stimmungsbild einholen ...
Ich fände es nett zu haben, aber für mich ist es nicht so besonders wichtig.

**Comment by phoebusryan** [comment]
@polarpixel Das wäre natürlich sinnvoll. Meines Wissens kann man bei Github aber keine Umfragen oder ähnliches erstellen.

**Comment by thielpeter** [comment]
Ich denke es ist nicht sinnvoll Editoren zu verbiegen, zudem sind Flyouts übersichtlicher.

**Comment by phoebusryan** [comment]
Umgebaut in Version 1.5.4

**Comment by tbaddade** [comment]
> zudem sind Flyouts übersichtlicher.

Da wiederspreche ich. Sie sind Platzsparender aber nich übersichtlicher. Sehe ich die Buttons gleich, klick fertig. Außerdem erkennt man die Flyouts aktuell nicht, so dass ein Klick immer eine Formatierung oder ein öffnen des Flyouts bedeutet. Was tatsächlich passiert muss man erlernen.

**Comment by skerbis** [comment]
Ich schlage vor beide Lösungen anzubieten. So kann sich jeder aussuchen was er favorisiert und die Profile anpassen wenn er das wünscht. Ich favorisiere die Flyaouts, weil platzsparender und weil es den anderen bekannten Editoren ähnlicher ist.

**Comment by phoebusryan** [comment]
Weiter gehts hier: #39
