### ISSUE TITLE
Überschrift "deaktivieren" verursacht Fehler

### ISSUE THREAD

**Issue by tbaddade** [phoebusryan/rex_redactor#19]
Zeile als "h3" ausgezeichnet. Danach klick nochmals auf "h3". Wurde wieder ein "h3" hinzugefügt und nicht das bisherige gelöscht. Außerdem wurde in das vorhanden "h3" ein leeres "li" eingefügt.

Das leere "h3" kann jetzt gar nicht mehr gelöscht werden. Daher ggf. vor dem speichern alle leeren HTML-Tags löschen?

**Comment by phoebusryan** [comment]
Das kann ich gerade nicht reproduzieren. Wie genau gehst du da vor?

**Comment by tbaddade** [comment]
```
Überschrift

Listenpunkt
Listenpunkt
Listenpunkt
Listenpunkt
```

Listenpunkte markiert und als ul-Liste gekennzeichnet, Überschrift markiert und als "h3" gekennzeichnet. Überschrift nochmals markiert und wieder "h3" in der Formatvorlage ausgewählt. Dann kommt es zum obigen Verhalten.

**Comment by tbaddade** [comment]
Passiert auch wenn man eine "h3" in "h4" umwandelt.

Zur Zeit muss man den Quelltext des Editors im Auge behalten damit man merkwürdige Notationen wieder löscht.

**Comment by tbaddade** [comment]
Ich habe das versucht direkt bei https://imperavi.com/redactor/ nachzustellen. Hier scheint der Fehler nicht zu passieren.

**Comment by polarpixel** [comment]
Dort läuft aber wohl die neue Version.
Man müsste dann wohl die jetzige Version als Stand-Alone probieren und vergleichen?

**Comment by phoebusryan** [comment]
Genau, die Version auf der Seite ist eine neuere. Ich habe dich in Skype geadded, Thomas. Ich sende dir dann mal die neuste Version, damit du es nachstellen kannst mit einer standalone Version.

**Comment by tbaddade** [comment]
In der standalone Version scheint obiges Verhalten nicht zu passieren.

**Comment by phoebusryan** [comment]
Ich kann dies leider nicht reproduzieren.
