### ISSUE TITLE
Notice bei http://redaxo/redaxo/index.php?page=rex_redactor/css

### ISSUE THREAD

**Issue by dergel** [phoebusryan/rex_redactor#2]
Notice: Undefined index: custom_css in /Users/jankristinus/Desktop/workspace/redaxo/redaxo/redaxo/src/addons/rex_redactor/pages/css.php on line 25

**Comment by phoebusryan** [comment]
Das ist mir bekannt und ist in 1.1.3 gefixt. Es tritt nun nur noch auf, wenn man das Addon geupdatet hat und daher schon eine Config hat: https://github.com/factorylabs/rex_redactor/blob/master/install.php

Schön wäre die Möglichkeit einen Configkey zu setzen, wenn es ihn nicht gibt. Also nicht generell abzufragen ob es den Key schon gibt sondern spezifisch für einen Key.

**Comment by phoebusryan** [comment]
Grade gesehen, dass das ja geht...
http://www.redaxo.org/docs/master/source-class-rex_package.html#108-111

Ich haue gleich ein Update raus.

**Comment by phoebusryan** [comment]
Gefixt in Version 1.1.4; siehe commit.
