### ISSUE TITLE
Mehrfaches "insertProfile" verhindern 

### ISSUE THREAD

**Issue by olien** [phoebusryan/rex_redactor#20]
Wenn ich 'insertProfile' im Modulinput benutze wird jedesmal wenn ich das Modul aufrufe ein Profil angelegt.

Wie kann ich das verhindern?

**Comment by phoebusryan** [comment]
Ich habe gerade die API erweitert, sodass dies möglich ist. Das Update folgt in Kürze.

if (!rex_redactor::profileExists('simple')) {
  rex_redactor::insertProfile('simple', 'Lorem Ipsum', 'relative', 'bold,italic', 'table');
}

**Comment by phoebusryan** [comment]
Fixed in Version 1.5.1
