### ISSUE TITLE
Wünsch: Formatting und Source

### ISSUE THREAD

**Issue by skerbis** [phoebusryan/rex_redactor#21]
Bitte wieder das Formatring einbauen und auch Source anbieten. 
Ich vermisse auch einen Button um Formatierungen zurückzusetzen. (Bereinigen)

**Comment by phoebusryan** [comment]
Source gibt es; es heisst einfach "html" uns muss unter Buttons eingefügt werden. Siehe https://github.com/factorylabs/rex_redactor/blob/master/pages/profiles.php#L93-L94

Das mit Formatting war eine recht lange Diskussion in Github (https://github.com/factorylabs/rex_redactor/issues/18) und später in Skype. Du kannst dich gerne noch dazu äussern bei dem Issue.

Ein Bereinigen-Button wäre grundsätzlich cool, da gebe ich dir recht. Spontan wüsste ich aber nicht wie ich es umsetzen soll. Ich schau mal in wie fern so etwas möglich ist ohne den ganzen Editor umschreiben zu müssen. ;)

**Comment by skerbis** [comment]
Es gibt eine Tastenkombination in Redactor dafür 
Mac:  CMD+SHIFT+M 
Windows: Ctrl + Shift + m
Hier ist noch was in der API
https://imperavi.com/redactor/docs/api/inline/#api-removeFormat

**Comment by phoebusryan** [comment]
Dies entfernt aber nur Inlinestyles. Ich habe nun bereits dies hier gefunden:
https://imperavi.com/redactor/docs/api/clean/#api-getPlainText

Das killt dann Tags und Inlinestyles. Ist im nächsten Update dann als Button verfügbar. ;-)

**Comment by phoebusryan** [comment]
Version 1.5.5 ist nun online. Das Plugin heisst 'cleaner'

**Comment by skerbis** [comment]
:-) Super - Danke
