### ISSUE TITLE
Farbfelder sowie Tabelle einfacher fehlen noch als Plugin

### ISSUE THREAD

**Issue by royalemotions** [phoebusryan/rex_redactor#23]
Farbfelder fehlen noch! Wir haben zwar nun eine Liste mit Farbklassen, aber keine Farbfelder, die man für den Text oder als Background hinter den Text setzen kann. Hier kommt nur der Pinsel zum Einsatz, benötige aber auch den Tropfen :)

Außerdem kann man Tabelle schöner machen.

Beispiele hier: https://www.froala.com/wysiwyg-editor
Icon mit dem "Tropfen" > name:Colours
Icon Tabelle > name:Insert Table

**Comment by phoebusryan** [comment]
Dafür gibts demnächst den Froala-Editor für Redaxo 5.

**Comment by royalemotions** [comment]
Merci!! Bis wann soll ich das Geld anweisen ??

Von meinem iPad gesendet
