### ISSUE TITLE
Bilder / Verlinkung + CSS

### ISSUE THREAD

**Issue by skerbis** [phoebusryan/rex_redactor#29]
Bei der Bearbeitung der Bilder würde ich gerne CSS Klassen den Bildern zuweisen können. 
z.B. für Rahmen, rund, Ausrichtung,Lightbox, komplette Breite usw..  

Bei der verlinkung würden  auch interne Links zu Medien und Seiten nützlich sein. 

Zusätzliche Parameter für die Verlinkung, wären ebenfalls nützlich. 
*_rel=  data-xyz=    *_
ggf. durch den Admin zu definieren und als Auswahl anbieten.

**Comment by phoebusryan** [comment]
Evtl. kann ich dies mit dem offiziellen Properties-Plugin umsetzen:
https://imperavi.com/redactor/plugins/properties/

Das Plugin ist zwar für Redactor 2 aber man kann es vermutlich relativ simpel für Version 1 umbauen.

**Comment by phoebusryan** [comment]
Gefixt in Version 2.0 (wird in einer Woche released)
