### ISSUE TITLE
update.php fehlt

### ISSUE THREAD

**Issue by dergel** [phoebusryan/rex_redactor#3]
wenn man den installer durchläuft und die version aktualisiert, wird die update.php nicht aufgerufen um eventuell fehlende dinge nachzuinstallieren.

in meinem fall war das die tabelle für die buttons die gefehlt hat und dadurch gab es exceptions und nur durch save_mode und redactor reinstall ging dann wieder alles.

**Comment by olien** [comment]
jupp. das hatte ich auch

**Comment by phoebusryan** [comment]
Fixed in version 1.3.0
