### ISSUE TITLE
Link Dropdown

### ISSUE THREAD

**Issue by marcohanke** [phoebusryan/rex_redactor#32]
Um externe Links hinzuzufügen muss ich im Moment noch den Button "link" einfügen. Jetzt habe ich aber 2 "Link-Buttons" Könnte man ein Dropdown unter dem Button erstellen mit Interner Link, Externer Link, E-Mailadresse?

**Comment by phoebusryan** [comment]
Die Lösung ist noch nicht optimal, ja. Ich werde das aber sicher mit Issue #28 lösen.

**Comment by phoebusryan** [comment]
Weiter gehts hier: #39
