### ISSUE TITLE
Eigene CSS-Klassen / formattingAdd

### ISSUE THREAD

**Issue by erraiva** [phoebusryan/rex_redactor#33]
Redactor individuell konfigurierbar machen. Möglichkeit, eigene CSS-Klassen zu benutzen.
Beispiel: https://imperavi.com/redactor/examples/formatting-add/

**Comment by phoebusryan** [comment]
Ist das noch relevant? Wenn ja, setze ich es auf die Todo.

**Comment by erraiva** [comment]
Hallo Thomas,
ja, das ist eine der Sachen, die ich für Redactor super fände.

Hier meine Wunschliste für Redactor:

_Eigene CSS-Klassen definieren_
und HTML-Elemente mit diesen belegen können.

_platzierte Bilder im Text_
Bildgrößen nur durch ziehen möglich, sie sollten per Pixeleingabe 
veränderbar sein, man möchte ja auch mal zwei Bilder gleich breit 
bekommen. Auch das Anhängen einer CSS-Klasse wäre hier cool

_Button "Formatierung entfernen"_
Der ausgewählte Text wird dupliziert, das führt bei Teiltexten 
ordentlich zu Verwirrung.

_Redactor ersetzt divs mit p:_
um das zu ändern, in der redactor.js: replaceDivs: false setzen

_Redactor HTML-Texte sind zu blass:_
.redactor-box textarea in der redactor.css: color ändern

_Bilder im Backend sind zu groß:_
In den Dateien
/assets/addons/redactor/redactor.css,
/assets/addons/redactor/redactor_custom.css und
/assets/addons/be_style/style.css die Bildbreite begrenzen

Die ersten beiden Punkte wären mir echt wichtig, die anderen sind eher 
lästig.
Aber vielen Dank, dass du dir überhaupt die Arbeit machst ;-)=

Herzlichen Gruß
Heinz

Am 31.05.2016 um 09:41 schrieb Thomas Kaegi:

**Comment by phoebusryan** [comment]
Punkt 1: Kommt nächste Woche mit einem Update
Punkt 2: Pixelangaben in der heutigen Zeit (Stichwort Responsive) halte ich für eine schlechte Idee. Was ist der Gedanke dahinter?
Punkt 3: Ist bekannt und in der nächsten Version gefixt.
Punkt 4: Kann man grundsätzlich einbauen
Punkt 5: Kommt nächste Woche mit einem Update
Punkt 6: Kommt nächste Woche mit einem Update

Btw. Kommst du am Samstag zum Redaxotag? Ich werde da sein und ausführlich über den Redactor berichten.

**Comment by erraiva** [comment]
Hallo Thomas, danke für die Antwort.
Es freut mich, dass da was möglich ist.

Eine genaue Einstellung der Bildbreiten ist doch sinnvoll, responsive 
hin oder her. Wenn ich ein Bild in einem Textabsatz haben möchte, der 
Text soll das Bild umfließen. Das kann ich zwar jetzt auch, indem ich 
das Bild kleiner ziehe, würde es aber lieber mit einer 
Eingabemöglichkeit auf eine bestimmte Breite bringen, weil z.B. der 
Absatz darunter auch ein Bild enthält, welches gleich breit sein soll.

Redaxo-Tag wäre eine Idee. Ich weiß noch nicht ob ich das schaffe, aber 
danke für den Tipp :-)

LG
Heinz

Am 31.05.2016 um 11:43 schrieb Thomas Kaegi:

**Comment by phoebusryan** [comment]
Hallo Heinz,
das mit der fixen Bilderbreite nehme ich mal auf.

Bzgl. Redaxotag: Ja unbedingt kommen und vor Ort mit allen Addonentwicklern und dem Coreteam diskutieren!
Anmeldung: http://www.redaxo.org/de/anmeldung-redaxo-tag-2016/
Teilnehmer: http://www.redaxo.org/de/anmeldung-redaxo-tag-2016/teilnehmerliste/
Themen: http://www.redaxo.org/de/forum/neuigkeiten-f1/redaxo-tag-2016-themen-t21120.html
Infos: http://www.redaxo.org/de/forum/neuigkeiten-f1/redaxo-tag-2016-mehr-infos-und-anmelden-t21067.html

Gruss Thomas

**Comment by phoebusryan** [comment]
Kleines Update:
Die Einstellung "replaceDivs" ist deprecated:
https://imperavi.com/redactor/docs/upgrading-to-redactor-ii/

Ich werde sie daher leider nicht einbauen.
