### ISSUE TITLE
Leerer Title-Tag bei einem Bild verhindert Rendern des korrekten Bildlinks

### ISSUE THREAD

**Issue by polarpixel** [phoebusryan/rex_redactor#35]
Wenn ein Bild über das Medienpool-Icon eingefügt wird und kein Ttile-Tag hinterelgt ist, erzeugt das einen Link wie:
!index.php?rex_media_type=markitupImage&rex_media_file=imag1016.jpg()!
Diese Zeile wird dann aber nicht via Textile gerendert.

Vorschlag: keine runden Klammer setzen, wenn das Title-Tag-Feld leer ist.

**Comment by polarpixel** [comment]
Siehe Diskussion im Forum:
http://www.redaxo.org/de/forum/post118339.html#p118339

**Comment by phoebusryan** [comment]
Ähm, kann ich gerne so anpassen aber da reden wir eher vom Markitup oder?

**Comment by polarpixel** [comment]
Natürlich! Ich bin mit Deinen vielen Editoren durcheinander gekommen ... ;-)
Ich schließe hier und mach das Issue beim korrekten Editor auf.
