### ISSUE TITLE
Dateilink in redactor funktioniert nicht

### ISSUE THREAD

**Issue by skerbis** [phoebusryan/rex_redactor#36]
http://www.redaxo.org/de/forum/addons-packages-f43/dateilink-in-redactor-funktioniert-nicht-t21081.html

**Comment by mbodon** [comment]
Hallo Thomas, ich bzw. meine Kunden warten auch sehnsüchtig auf dieses "kleine" Update. Woran scheitert es? Kann ich dir helfen? (Habe selber aber nur sehr einfache Programmierkenntnisse)

**Comment by phoebusryan** [comment]
Aktuell scheitert es an der Zeit. Ich wollte mich dem und anderen Issues im Mai annehmen. Vorher komme ich wohl leider nicht dazu. Vermutlich ist es keine allzu grosse Sache, Gregor Harlan aus dem Core-Team hat nämlich schon einige Vorbereitungen für diesen Fix gemacht. Trotzdem scheitert es im Moment an der Zeit. Kannst du noch warten bis Mai?

**Comment by mbodon** [comment]
Danke für die Info und für deine gute Arbeit. Mai ist super ...

**Comment by phoebusryan** [comment]
Gefixt in Version 2.0 (wird in einer Woche released)
