### ISSUE TITLE
Dropdown oder nicht?

### ISSUE THREAD

**Issue by phoebusryan** [phoebusryan/rex_redactor#39]
Immer wieder werde ich angefragt oder erhalte Issues ob ich wohl ein Dropdown bei einem Button machen könnte um ähnliche Buttons (z.B. Links oder Headlines) zu gruppieren. Wieder andere User möchten eben genau das nicht. Das bringt mich in eine Zwickmühle, weil ich nicht alles doppelt entwickeln möchte. Issues die dieses Problem betreffen: #18 #21 #32 

Nun einfach die Frage. Wie soll ich es lösen, damit alle Glücklich sind? Ich persönlich bin absolut für Gruppen/Dropdown/Flyouts weil viele andere Buttons (z.B. Farben) auch so funktionieren. Es wäre einfach einheitlicher.

Was meint ihr?

**Comment by polarpixel** [comment]
Ich bin auch für Flyouts: Aber: Wichtig fände ich es, dass man selbst definieren kann, welche Buttons man in einem Flyout gruppieren kann. So könnte z.B. h1-h3 im Flyout zusammenfassen, wenn ich bei einer Website viele sonstige Buttons brauche. Und sie nebeneinander setzen, wenn ich nur ganz wenige brauche.

Diese Flexibilität. das selbst definieren zu können, ist aber schwierig umzusetzen, wenn ich mich richtig erinnere?

**Comment by phoebusryan** [comment]
Ja, das ist richtig. Die meisten Buttons sind eh hardcoded im Redactor-Core. Ich habe die meisten davon aber bereits aus dem Core entfernt, damit ich es überhaupt irgendwie lösen kann (Sehr unschön den Core zu verändern!) ... Demnächst erscheint ja Redactor 3. Damit geht hoffentlich alles viel leichter. Aktuell gibts aber noch keine Details dazu.

**Comment by marcohanke** [comment]
Auf jeden Fall Dropdown. Für simple Editoren mag das theoretisch ohne schöner sein, aber sobald es etwas komplexer wird, geht es eigentlich nicht ohne. Gerade im Linkfall (E-Mail Link, Interner Link, Externer Link) stelle ich mir es sehr komisch vor, 3 Linksymbole nebeneinander zu haben. Weiter geht es mit eigenen Buttons oder Formaten. Ich hab in der Regel mehrere Button Typen. Ohne Dropdown wird dass ein Chaos.

**Comment by phoebusryan** [comment]
Gefixt in Version 2.0 (wird in einer Woche released)
