### ISSUE TITLE
Seltsames Problem beim Bearbeiten von Texten

### ISSUE THREAD

**Issue by alexschuengel** [phoebusryan/rex_redactor#46]
ich setze bei einigen Projekten den redactor2 ( 3.1.1) als Texteditor ein. Leider kommt es bei mir sehr häufig zu "seltsamen" Fehlern beim Eingeben und Bearbeiten von Texten. Wenn ich einen Absatz setzen will springt der Cursor mal an den Anfang, mal ans Ende. Oder es wird kein Absatz gesetzt, stattdessen zerschießt es den kompletten Text. Auch stelle ich fest, dass häufig leere Absätze <p></p> gesetzt werden. Oder wenn ich eine Liste <ul> habe, die ich bearbeiten möchte werden willküllrich <p> zu den Listenpunkten hinzugefügt....

Also alles in allem sehr schwer bzw gar nicht möglich, über den Editor Texte zu bearbeiten. Ich helfe mir häufig mit dem Quelltext aus, und bearbeite dort direkt. Aber das ist a) sicher nicht die Idee von redactor und b) für meine Kunden nicht möglich.

Hat jemand ähnliche Probleme, oder einen Tipp wo ich anfangen kann nach der Ursache zu suchen??

Grüße Alex

**Comment by tbaddade** [comment]
Das AddOn liegt bei FOR
https://github.com/FriendsOfREDAXO/redactor2
