### ISSUE TITLE
1.3.4 Bug - Beim erneuten Aufruf 

### ISSUE THREAD

**Issue by skerbis** [phoebusryan/rex_redactor#5]
TypeError: undefined is not an object (evaluating 'func[0]')
(anonyme Funktion)redactor.js:47
eachjquery.min.js:1:2886
eachjquery.min.js:1:851
redactorredactor.js:39
redactorInitredactor_profiles.js:3
(anonyme Funktion)redactor_profiles.js:20
dispatchjquery.js:784
handlejquery.js:424
triggerjquery.js:683
(anonyme Funktion)jquery.js:1350
eachjquery.min.js:1:2886
eachjquery.min.js:1:851
triggerjquery.js:1347
djquery-pjax.min.js:2:276
successjquery-pjax.min.js:6
jjquery.min.js:1:26930
fireWithjquery.min.js:1:27739
xjquery.js:4873
(anonyme Funktion)jquery.js:5209

![bildschirmfoto 2015-12-01 um 13 22 18](https://cloud.githubusercontent.com/assets/791247/11500819/d5b12130-982f-11e5-9484-1a530eaddc85.png)

**Comment by phoebusryan** [comment]
Aktuell kann ich das nicht reproduzieren; wie genau gehst du vor? Hast du als Moduleinput mein Beispiel benutzt?

**Comment by skerbis** [comment]
Ja ich habe exakt Dein Beispiel verwendet um es zu reproduzieren. 
Browser: Safari 9.0.1 und Firefox 42

![bildschirmfoto 2015-12-01 um 13 53 33](https://cloud.githubusercontent.com/assets/791247/11501249/fec3d376-9832-11e5-8b78-98124539c3eb.png)

**Comment by skerbis** [comment]
Das geschieht, wenn man direkt nach dem Speichern den Block noch mal bearbeiten will.

**Comment by phoebusryan** [comment]
Hm, wenn ich auf "speichern" oder auch "übernehmen" klicke, klappt es bei mir wenn ich danach weiter bearbeiten möchte. Kannst du mir evtl. mal einen Zugang zu deiner Umgebung geben?

**Comment by skerbis** [comment]
Wie kann ich Dir ne private Message schicken?

**Comment by phoebusryan** [comment]
entweder via skype (bist du im rex_radio drin?) oder evtl. am einfachsten im Forum: http://www.redaxo.org/de/forum/ucp.php?i=pm&mode=compose&u=10463

**Comment by phoebusryan** [comment]
Danke für den Zugang; ich weiss jetzt was du meinst und kann es bei mir reproduzieren. Ich gehe der Sache nach.

**Comment by skerbis** [comment]
Super. 
Brauchst Du den Zugang noch?

**Comment by phoebusryan** [comment]
Nein; kannst du löschen.

**Comment by phoebusryan** [comment]
Gelöst via Hotfix in 1.3.5

**Comment by skerbis** [comment]
Super. Funktioniert :-)
