### ISSUE TITLE
Safari 9.0.1 - Taste "l"

### ISSUE THREAD

**Issue by skerbis** [phoebusryan/rex_redactor#6]
Es gibt einen merkwürdigen Effekt bei Safari. Sobald ich die Taste l (kleines L) drücke, werde ich ausgeloggt. Anscheinend wird der Accesskey fürs Logout ausgelöst. 
In Chrome und Firefox (alles Mac) taucht das Problem nicht auf. Merkwürdig. 

Getestet in aktuellem und und einem alten Stand von REX5
Safari 9.0.1 El Capitan und Yosemite

**Comment by tbaddade** [comment]
Ist behoben
https://github.com/redaxo/redaxo/issues/488
https://github.com/redaxo/redaxo/commit/76bb416cc69f177e42099fa8f39bdffecbb58304

**Comment by skerbis** [comment]
Super :+1:

**Comment by skerbis** [comment]
Stimmt :+1:
